# Generated by Django 4.2.13 on 2024-07-05 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=10)),
                ('player2', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
                ('mode', models.CharField(choices=[('1VS1', '1 vs 1'), ('TOURNAMENT', 'Tournament')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_game1', to='game.game')),
                ('game2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_game2', to='game.game')),
                ('game3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_game3', to='game.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.tournament'),
        ),
    ]
