# Generated by Django 4.2.13 on 2024-07-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('1VS1', '1vs1'), ('TOURNAMENT', 'Tournament')], max_length=10),
        ),
    ]
