# Generated by Django 5.0.6 on 2024-07-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('usual_full_name', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=255)),
                ('image_link', models.URLField(max_length=255)),
            ],
        ),
    ]
