# Generated by Django 5.0.6 on 2024-07-11 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('usual_full_name', models.CharField(max_length=50)),
                ('image_link', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OTPSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=50)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
