"""
Django settings for pong project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from os import getenv, path

import string
import random

load_dotenv(verbose=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
chars = (
    "".join([string.ascii_letters, string.digits, string.punctuation])
    .replace("'", "")
    .replace('"', "")
    .replace("\\", "")
)
SECRET_KEY = "".join([random.SystemRandom().choice(chars) for i in range(50)])

INSTALLED_APPS = [
    # "Make sure "daphne" is at the top
    "daphne",
    "authentication",
    "game",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    # TODO: need set allowed host
    # 'django.middleware.csrf.CsrfViewMiddleware',
]

ROOT_URLCONF = "pong.urls"

WSGI_APPLICATION = "pong.wsgi.application"
ASGI_APPLICATION = "pong.asgi.application"


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Seoul"

USE_TZ = False

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

CORS_ALLOW_HEADERS = (
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
)
