from os import getenv

JWT_EXPIRED = 7150
TOKEN_EXPIRES = 14000
LOCK_ACCOUNT = 900
MAX_ATTEMPTS = 5
API_URL = getenv("API_URL")
JWT_SECRET = getenv("JWT_SECRET")
INTRA_UID = getenv("INTRA_UID")
INTRA_SECRET_KEY = getenv("INTRA_SECRET_KEY")
REDIRECT_URI = getenv("REDIRECT_URI")
STATE = getenv("STATE")
AUTH_PAGE = getenv("AUTH_PAGE")
FRONT_BASE_URL = getenv("FRONT_BASE_URL")
