name: django CD in EC2

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: connect ec2 instance
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/pong/pong
            git pull https://${{ secrets.GIT_USER }}:${{ secrets.GIT_PASSWORD }}@github.com/ft-transcendence-o/backend.git
            cd /home/ubuntu/pong
            sudo docker compose down
            sudo docker compose up --build -d
