name: django CI and CD in EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # specify the Python version you are using

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        env:
          HASH_SALT: ${{ secrets.HASH_SALT }}
          INTRA_UID: ${{ secrets.INTRA_UID }}
          INTRA_SECRET_KEY: ${{ secrets.INTRA_SECRET_KEY }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          API_URL: ${{ secrets.API_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          STATE: ${{ secrets.STATE }}
        run: |
          python pong/manage.py test --settings=pong.settings.test
    
      - name: connect ec2 instance
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/transcen/backend/pong
            git pull https://${{ secrets.GIT_USER }}:${{ secrets.GIT_PASSWORD }}@github.com/ft-transcendence-o/backend.git
            cd /home/ubuntu/transcen
            sudo docker compose down
            sudo docker compose up --build -d
